CREATE SEQUENCE  ANALYTICS_EVENT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 ;
CREATE TABLE ANALYTICS_EVENT(
                                EVENT_TIME TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                ID NUMBER NOT NULL,
                                USER_ID VARCHAR2(36) NOT NULL,
                                IP_ADDRESS VARCHAR2(45),
                                BROWSER_LANGUAGE VARCHAR2(16),
                                USER_AGENT VARCHAR2(2048),
                                CLIENT_ID VARCHAR2(255) NOT NULL,
                                EVENT VARCHAR2(64) NOT NULL,
                                PAGE VARCHAR2(255) NOT NULL
);
ALTER TABLE ANALYTICS_EVENT ADD CONSTRAINT ANALYTICS_EVENT_PK PRIMARY KEY(ID);
CREATE TABLE ANALYTICS_EVENT_ATTRIBUTE(
                                          ANALYTICS_EVENT_ID NUMBER NOT NULL,
                                          ATTRIBUTE_NAME VARCHAR2(255) NOT NULL,
                                          ATTRIBUTE_VALUE VARCHAR2(1024)
);
ALTER TABLE ANALYTICS_EVENT_ATTRIBUTE ADD CONSTRAINT ANALYTICS_EVENT_ATTRIBUTE_PK PRIMARY KEY(ANALYTICS_EVENT_ID, ATTRIBUTE_NAME);
CREATE TABLE AUTHORIZED_CLIENT_ORIGIN(
                                         AUTHORIZED_ORIGIN VARCHAR2(255),
                                         CLIENT_ID VARCHAR2(255) NOT NULL
);
ALTER TABLE AUTHORIZED_CLIENT_ORIGIN ADD CONSTRAINT AUTHORIZED_CLIENT_ORIGIN_PK PRIMARY KEY(AUTHORIZED_ORIGIN,CLIENT_ID);
CREATE TABLE TRACK_CLIENT(
                             ID VARCHAR2(255) NOT NULL,
                             NAME VARCHAR2(255)
);
ALTER TABLE TRACK_CLIENT ADD CONSTRAINT TRACK_CLIENT_PK PRIMARY KEY(ID);
ALTER TABLE ANALYTICS_EVENT_ATTRIBUTE ADD CONSTRAINT ANALYTICS_EVENT_ATTRIBUTE_FK1 FOREIGN KEY(ANALYTICS_EVENT_ID) REFERENCES ANALYTICS_EVENT(ID);
ALTER TABLE AUTHORIZED_CLIENT_ORIGIN ADD CONSTRAINT AUTHORIZED_CLIENT_ORIGIN_FK1 FOREIGN KEY(CLIENT_ID) REFERENCES TRACK_CLIENT(ID);
